server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: boleta-service
              uri: lb://boletas  
              predicates:
                - Path=/api/v1/boletas/**, /boletas/api-docs/**

            - id: cliente-service
              uri: lb://clientes 
              predicates:
                - Path=/api/v1/clientes/**, /clientes/api-docs/**

            - id: producto-service
              uri: lb://producto 
              predicates:
                - Path=/api/v1/productos/**, /productos-api-docs/**
                
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    urls:
      - name: Microservicio Boletas
        url: /boletas/api-docs
      - name: Microservicio Clientes
        url: /clientes/api-docs
      - name: Microservicio Productos
        url: /productos-api-docs
  api-docs:
    enabled: true